
classdef Anchor < ros.Message
    %Anchor MATLAB implementation of ros_decawave/Anchor
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ros_decawave/Anchor' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '3c1d783d1e22339670e2979c9c5e3db4' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'X' 'Y' 'Z' 'Qf' 'Distance' 'DistQf' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'x' 'y' 'z' 'qf' 'distance' 'dist_qf' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
			 '' ...
			 '' ...
			 '' ...
			 '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        X
        Y
        Z
        Qf
        Distance
        DistQf
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'Anchor', 'Header')
            obj.Header = val;
        end
        function set.X(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Anchor', 'X');
            obj.X = double(val);
        end
        function set.Y(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Anchor', 'Y');
            obj.Y = double(val);
        end
        function set.Z(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Anchor', 'Z');
            obj.Z = double(val);
        end
        function set.Qf(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Anchor', 'Qf');
            obj.Qf = double(val);
        end
        function set.Distance(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Anchor', 'Distance');
            obj.Distance = double(val);
        end
        function set.DistQf(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Anchor', 'DistQf');
            obj.DistQf = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ros_decawave.Anchor.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ros_decawave.Anchor;
            obj.reload(strObj);
        end
    end
end
