// Generated by gencpp from file amr/odrive.msg
// DO NOT EDIT!


#ifndef AMR_MESSAGE_ODRIVE_H
#define AMR_MESSAGE_ODRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace amr
{
template <class ContainerAllocator>
struct odrive_
{
  typedef odrive_<ContainerAllocator> Type;

  odrive_()
    : header()
    , left_vel(0)
    , right_vel(0)  {
    }
  odrive_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_vel(0)
    , right_vel(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _left_vel_type;
  _left_vel_type left_vel;

   typedef int16_t _right_vel_type;
  _right_vel_type right_vel;





  typedef boost::shared_ptr< ::amr::odrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amr::odrive_<ContainerAllocator> const> ConstPtr;

}; // struct odrive_

typedef ::amr::odrive_<std::allocator<void> > odrive;

typedef boost::shared_ptr< ::amr::odrive > odrivePtr;
typedef boost::shared_ptr< ::amr::odrive const> odriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amr::odrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amr::odrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace amr

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'amr': ['/home/tanishqjain/catkin_ws/src/aug2per/matlab_msg_gen_ros1/glnxa64/src/amr/msg'], 'std_msgs': ['/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/usr/local/MATLAB/R2020b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::amr::odrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr::odrive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr::odrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr::odrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr::odrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr::odrive_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amr::odrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fee1aba673a70a9570d354c2566343f8";
  }

  static const char* value(const ::amr::odrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfee1aba673a70a95ULL;
  static const uint64_t static_value2 = 0x70d354c2566343f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::amr::odrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amr/odrive";
  }

  static const char* value(const ::amr::odrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amr::odrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int16 left_vel\n"
"int16 right_vel\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::amr::odrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amr::odrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_vel);
      stream.next(m.right_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct odrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amr::odrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amr::odrive_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_vel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_vel);
    s << indent << "right_vel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMR_MESSAGE_ODRIVE_H
