
classdef AnchorArray < ros.Message
    %AnchorArray MATLAB implementation of ros_decawave/AnchorArray
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ros_decawave/AnchorArray' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '57f47863c037d488af1159bddb78915c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Anchors' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'anchors' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
			 'ros.msggen.ros_decawave.Anchor' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Anchors
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'AnchorArray', 'Header')
            obj.Header = val;
        end
        function set.Anchors(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.ros_decawave.Anchor.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.ros_decawave.Anchor'};
            validateattributes(val, validClasses, validAttributes, 'AnchorArray', 'Anchors')
            obj.Anchors = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ros_decawave.AnchorArray.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ros_decawave.AnchorArray;
            obj.reload(strObj);
        end
    end
end
